config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktails_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path, notice: 'Cocktail was successfully destroyed.'
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new
    @ingredients = Ingredient.all
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="container form">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name, label: 'Cocktail name:' %>
    </div>
    <div class="cocktai-photo">
      <%= f.input :photo, as: :file, label: 'Photo:' %>
    </div>
    <div class="form-actions text-center">
      <%= f.button :submit %>
      <%= link_to 'Cocktails List', cocktails_path, class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render "form" %>

app/views/cocktails/index.html.erb
<div class="container">
    <div class='container-home display-grid'>
      <% @cocktails.each do |cocktail| %>
        <div class="cocktail-card grid-item">
          <div class='name text-center'>
            <%= cocktail.name%>
          </div>

          <div class='cocktail-photo'>
            <%= cl_image_tag cocktail.photo.key, height: 200, width: 200, crop: :fill %>
            <ul>
              <% cocktail.doses.each do |dose| %>
                <li><%= dose.description %> - <%= dose.ingredient.name %></li>
              <% end %>
            </ul>
          </div>
          
          <div class='card-links text-center'>
            <%= link_to 'Delete', cocktail, method: :delete, data: {confirm: 'Are you sure'}, class: 'btn' %>
            <%= link_to 'Edit', edit_cocktail_path(cocktail), class: 'btn' %>
            <%= link_to 'Show', cocktail, class: 'btn' %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<%= render "form" %>

app/views/cocktails/show.html.erb
<div class='container'>
  <div class='container-show center'>
    <div class="cocktail-card grid-item">
      <div class='name text-center'>
        <%= @cocktail.name%>
      </div>

      <div class='cocktail-photo'>
        <%= cl_image_tag @cocktail.photo.key, height: 200, width: 200, crop: :fill %>
        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li><%= dose.description %> - <%= dose.ingredient.name %></li>
          <% end %>
        </ul>
      </div>
      <div class='card-links text-center'>
        <%= link_to 'New Dose', new_cocktail_dose_path(@cocktail), class: 'btn' %>
        <%= link_to 'Cocktails List', cocktails_path, class: 'btn' %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container form">
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <h2><%= @cocktail.name %> </h2>
      <%= f.input :description %>
      <%= f.association :ingredient, collection: @ingredients %>
    </div>

    <div class="form-actions text-center">
      <%= f.button :submit %>
      <%= link_to 'Cocktails List', cocktails_path, class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="">
      <%= render "shared/banner" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_banner.html.erb
<header>
	<div class="overlay">
    <h1>Welcome to Alleslana Drink Bar</h1>
	  <button><%= link_to ' Create Your Cocktail ', new_cocktail_path, class: 'btn-banner' %></button>
	</div>
</header>